# Generated by Django 5.2.7 on 2025-10-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ishkuni',
            name='miqdor',
        ),
        migrations.AddField(
            model_name='ishkuni',
            name='soni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='narxi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodim',
            name='ish_haqi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='lavozim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
