# Generated by Django 5.2.7 on 2025-10-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0002_remove_ishkuni_miqdor_ishkuni_soni_mahsulot_narxi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='ishga_kirilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
