# Generated by Django 5.2.7 on 2025-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0003_xodim_ishga_kirilgan_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='bolim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
