# Generated by Django 5.2.7 on 2026-10-02 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0004_xodim_bolim_xodim_telefon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ishkuni',
            options={'verbose_name': 'Ish kuni', 'verbose_name_plural': 'Ish kunlari'},
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='xodim',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AddField(
            model_name='xodim',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodim_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
