# Generated by Django 5.2.7 on 2026-10-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ish', '0005_alter_ishkuni_options_alter_mahsulot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Admin tomonidan tasdiqlangan'),
        ),
    ]
